# run db service
services:
  db:
    image: postgres:16
    restart: unless-stopped # just restart if crashes, only stop with docker compose down or docker stop
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oont_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db # start the db first
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/oont_db?schema=public"
      PORT: "3000"
    ports:
      - "3000:3000" #container:localhost
volumes:
  postgres_data:



