# run db service
services:
  db:
    image: postgres:16
    restart: unless-stopped # just restart if crashes, only sto-p with docker compose down or docker stop
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oont_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: